//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.24 at 09:33:10 PM IST 
//


package localhost._8080.ns.employee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.ns.employee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmployeeDetailsRequest1_QNAME = new QName("http://localhost:8080/ns/employee", "employeeDetailsRequest1");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.ns.employee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeeDetailsRequest }
     * 
     */
    public EmployeeDetailsRequest createEmployeeDetailsRequest() {
        return new EmployeeDetailsRequest();
    }

    /**
     * Create an instance of {@link EmployeeDetailsResponse }
     * 
     */
    public EmployeeDetailsResponse createEmployeeDetailsResponse() {
        return new EmployeeDetailsResponse();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/ns/employee", name = "employeeDetailsRequest1")
    public JAXBElement<Object> createEmployeeDetailsRequest1(Object value) {
        return new JAXBElement<Object>(_EmployeeDetailsRequest1_QNAME, Object.class, null, value);
    }

}
